using System;
using System.Collections.Generic;
using System.Text;

namespace ODMIS_Homework2
{
    public enum OpCode
    {
        LOADA_M,
        LOADA_R,
        LOADI_I,
        LOADI_D,
        STORE_M,
        STORE_R,
        ADDA_I,
        ADDA_D,
        SUBA_I,
        SUBA_D,
        DIVA_I,
        DIVA_D,
        MULA_I,
        MULA_D,
        ADDI_I,
        ADDI_D,
        SUBI_I,
        SUBI_D,
        DIVI_I,
        DIVI_D,
        MULI_I,
        MULI_D,
        ROOT_I,
        ROOT_D,
        CEIL,
        FLOOR,
        ROUND,
        RAND_I,
        RAND_D,
        PI,
        CLEAR_R,
        CLEAR_M,
        JUMP,
        JUMP_LTE,
        JUMP_LT,
        JUMP_GTE,
        JUMP_GT,
        JUMP_EQ,
        ORA_R,
        ORI_I,
        ANDA_R,
        ANDI_I,
        NOTA_R,
        NOT_I,
        TERN_LTE,
        TERN_LT,
        TERN_GTE,
        TERN_GT,
        TERN_EQ,
        TIME,
        END
    }
}
